---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Check ESLint version
        run: yarn eslint -v
      - name: Run linter
        run: yarn lint -- --debug
      # - name: Run linter
      #   run: yarn lint
