---
name: Build and test
on:
  push:
    branches:
      - main

env:
  ESLINT_USE_FLAT_CONFIG: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn lint
      - name: Start web server
        run: yarn start 
      # - name: Wait for server to be ready
      #   run: |
      #     while ! nc -z localhost 3000; do   
      #       sleep 1
      #     done
      - name: Test application
        run: yarn test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jonaspauwels/webapp:latest
